<?php

/*
 * Daftar kepala sekolah, wakil kepala bidang, guru mapel, dan staff/karyawan.
 */

return [
    'kepala_sekolah' => [
        'nama' => 'Abror S.Hum M.Pd',
        'slug' => 'abror-s-hum-m-pd',
        'foto' => 'images/profileguru/pabror.webp',
        'pendidikan' => 'S2 Manajemen Pendidikan',
        'keahlian' => 'Leadership & Digital Pedagogy',
        'jabatan' => 'Kepala Sekolah',
        'motto' => 'Belajar bukan sekedar mencari nilai, tapi membangun masa depan',
        'email' => 'abror@smktelkom-sda.sch.id',
        'deskripsi' => 'Guru yang berfokus pada pengembangan karakter dan keterampilan digital siswa, khususnya di bidang jaringan komputer dan teknologi informasi.',
    ],
    'waka_bidang' => [
        [
            'nama' => 'Rachel Apriliani, S.Psi',
            'slug' => 'rachel-apriliani',
            'foto' => 'images/profileguru/rachel.webp',
            'jabatan' => 'Wakil Kepala Bidang Kesiswaan',
            'pendidikan' => 'S1 Psikologi Pendidikan',
            'keahlian' => 'Bimbingan Konseling',
            'email' => 'rachel@smktelkom-sda.sch.id',
            'deskripsi' => 'Guru yang berfokus pada pengembangan karakter dan kemampuan digital siswa dengan spesialisasi di bidang Bimbingan dan Konseling.',
        ],
        [
            'nama' => 'Bambang Sudarsono, S.Pd',
            'slug' => 'bambang-sudarsono',
            'foto' => 'images/profileguru/rachel.webp',
            'jabatan' => 'Wakil Kepala Bidang Kurikulum',
            'pendidikan' => 'S1 Pendidikan Teknologi Informasi',
            'keahlian' => 'Kurikulum Vokasi Digital',
            'email' => 'kurikulum@smktelkom-sda.sch.id',
            'deskripsi' => 'Bertanggung jawab atas penyusunan dan sinkronisasi kurikulum vokasi berbasis teknologi digital bersama mitra industri.',
        ],
        [
            'nama' => 'Hendra Setiawan, S.T',
            'slug' => 'hendra-setiawan',
            'foto' => 'images/profileguru/adi.webp',
            'jabatan' => 'Wakil Kepala Bidang Hubungan Industri',
            'pendidikan' => 'S1 Teknik Telekomunikasi',
            'keahlian' => 'Hubungan Industri & Magang',
            'email' => 'hubin@smktelkom-sda.sch.id',
            'deskripsi' => 'Mengembangkan jejaring kemitraan strategis dengan dunia usaha dan industri untuk magang siswa dan rekrutmen kerja alumni.',
        ],
        [
            'nama' => 'Agus Wahyudi, S.T',
            'slug' => 'agus-wahyudi',
            'foto' => 'images/profileguru/pabror.webp',
            'jabatan' => 'Wakil Kepala Bidang Sarana & Prasarana',
            'pendidikan' => 'S1 Teknik Komputer',
            'keahlian' => 'Manajemen Fasilitas & Lab',
            'email' => 'sarpras@smktelkom-sda.sch.id',
            'deskripsi' => 'Memastikan seluruh laboratorium komputer, jaringan fiber optik, dan gedung sekolah berada dalam standar industri prima.',
        ],
        [
            'nama' => 'Dewi Sartika, M.Pd',
            'slug' => 'dewi-sartika',
            'foto' => 'images/profileguru/ike.webp',
            'jabatan' => 'Wakil Kepala Bidang Penjaminan Mutu',
            'pendidikan' => 'S2 Administrasi Pendidikan',
            'keahlian' => 'Sistem Manajemen Mutu ISO 21001',
            'email' => 'mutu@smktelkom-sda.sch.id',
            'deskripsi' => 'Mengawal standarisasi manajemen mutu ISO pendidikan internasional di lingkungan SMK Telkom Sidoarjo.',
        ],
        [
            'nama' => 'Ferry Anugerah, S.Kom',
            'slug' => 'ferry-anugerah',
            'foto' => 'images/profileguru/adi.webp',
            'jabatan' => 'Wakil Kepala Bidang Digitalisasi Sekolah',
            'pendidikan' => 'S1 Sistem Informasi',
            'keahlian' => 'Smart School Platform',
            'email' => 'digital@smktelkom-sda.sch.id',
            'deskripsi' => 'Mengembangkan ekosistem digitalisasi sistem sekolah, aplikasi e-learning, dan automasi pembelajaran terpadu.',
        ],
        [
            'nama' => 'Maya Anggraini, S.Pd',
            'slug' => 'maya-anggraini',
            'foto' => 'images/profileguru/rachel.webp',
            'jabatan' => 'Wakil Kepala Bidang Keasramaan & Karakter',
            'pendidikan' => 'S1 Bimbingan Konseling',
            'keahlian' => 'Pendidikan Karakter & Kedisiplinan',
            'email' => 'karakter@smktelkom-sda.sch.id',
            'deskripsi' => 'Membina kedisiplinan, akhlak, dan integritas mental siswa sebagai pondasi lulusan vokasi yang tangguh.',
        ],
        [
            'nama' => 'Rizky Pratama, S.ST',
            'slug' => 'rizky-pratama',
            'foto' => 'images/profileguru/adi.webp',
            'jabatan' => 'Wakil Kepala Bidang Kewirausahaan & UPJ',
            'pendidikan' => 'D4 Manajemen Informatika',
            'keahlian' => 'Business Incubator & Startup',
            'email' => 'upj@smktelkom-sda.sch.id',
            'deskripsi' => 'Memimpin unit produksi jasa (UPJ) dan inkubator bisnis siswa untuk melatih kemampuan technopreneurship.',
        ],
    ],
    'guru_mapel' => [
        [
            'nama' => 'Ike Yuliastuti, S.Kom',
            'slug' => 'ike-yuliastuti-skom',
            'foto' => 'images/profileguru/pabror.webp',
            'mapel' => 'Guru Produktif SIJA',
            'jabatan' => 'Guru Produktif SIJA',
            'pendidikan' => 'S1 / S2 Pendidikan Vokasi Terakreditasi',
            'keahlian' => 'Guru Produktif SIJA & Digital Learning',
            'email' => 'ike-yuliastuti@smktelkom-sda.sch.id',
            'deskripsi' => 'Guru pengajar profesional yang berdedikasi membimbing dan mengasah kompetensi siswa SMK Telkom Sidoarjo di bidang Guru Produktif SIJA.',
        ],
        [
            'nama' => 'Muhammad Adi Riswanto, S.T',
            'slug' => 'muhammad-adi-riswanto-st',
            'foto' => 'images/profileguru/adi.webp',
            'mapel' => 'Guru Produktif TJAT',
            'jabatan' => 'Guru Produktif TJAT',
            'pendidikan' => 'S1 / S2 Pendidikan Vokasi Terakreditasi',
            'keahlian' => 'Guru Produktif TJAT & Digital Learning',
            'email' => 'muhammad-adi-riswanto@smktelkom-sda.sch.id',
            'deskripsi' => 'Guru pengajar profesional yang berdedikasi membimbing dan mengasah kompetensi siswa SMK Telkom Sidoarjo di bidang Guru Produktif TJAT.',
        ],
        [
            'nama' => 'Ahmad Fajar Santoso, S.Kom',
            'slug' => 'ahmad-fajar-santoso-skom',
            'foto' => 'images/profileguru/ike.webp',
            'mapel' => 'Guru Produktif SIJA',
            'jabatan' => 'Guru Produktif SIJA',
            'pendidikan' => 'S1 / S2 Pendidikan Vokasi Terakreditasi',
            'keahlian' => 'Guru Produktif SIJA & Digital Learning',
            'email' => 'ahmad-fajar-santoso@smktelkom-sda.sch.id',
            'deskripsi' => 'Guru pengajar profesional yang berdedikasi membimbing dan mengasah kompetensi siswa SMK Telkom Sidoarjo di bidang Guru Produktif SIJA.',
        ],
        [
            'nama' => 'Siti Nurhaliza, S.Pd',
            'slug' => 'siti-nurhaliza-spd',
            'foto' => 'images/profileguru/adi.webp',
            'mapel' => 'Guru Bahasa Inggris',
            'jabatan' => 'Guru Bahasa Inggris',
            'pendidikan' => 'S1 / S2 Pendidikan Vokasi Terakreditasi',
            'keahlian' => 'Guru Bahasa Inggris & Digital Learning',
            'email' => 'siti-nurhaliza@smktelkom-sda.sch.id',
            'deskripsi' => 'Guru pengajar profesional yang berdedikasi membimbing dan mengasah kompetensi siswa SMK Telkom Sidoarjo di bidang Guru Bahasa Inggris.',
        ],
        [
            'nama' => 'Dwi Cahyo Utomo, M.Pd',
            'slug' => 'dwi-cahyo-utomo-mpd',
            'foto' => 'images/profileguru/pabror.webp',
            'mapel' => 'Guru Matematika',
            'jabatan' => 'Guru Matematika',
            'pendidikan' => 'S1 / S2 Pendidikan Vokasi Terakreditasi',
            'keahlian' => 'Guru Matematika & Digital Learning',
            'email' => 'dwi-cahyo-utomo@smktelkom-sda.sch.id',
            'deskripsi' => 'Guru pengajar profesional yang berdedikasi membimbing dan mengasah kompetensi siswa SMK Telkom Sidoarjo di bidang Guru Matematika.',
        ],
        [
            'nama' => 'Budi Setiawan, S.T',
            'slug' => 'budi-setiawan-st',
            'foto' => 'images/profileguru/ike.webp',
            'mapel' => 'Guru Produktif TJAT',
            'jabatan' => 'Guru Produktif TJAT',
            'pendidikan' => 'S1 / S2 Pendidikan Vokasi Terakreditasi',
            'keahlian' => 'Guru Produktif TJAT & Digital Learning',
            'email' => 'budi-setiawan@smktelkom-sda.sch.id',
            'deskripsi' => 'Guru pengajar profesional yang berdedikasi membimbing dan mengasah kompetensi siswa SMK Telkom Sidoarjo di bidang Guru Produktif TJAT.',
        ],
        [
            'nama' => 'Rina Marlina, S.Pd',
            'slug' => 'rina-marlina-spd',
            'foto' => 'images/profileguru/pabror.webp',
            'mapel' => 'Guru Bahasa Indonesia',
            'jabatan' => 'Guru Bahasa Indonesia',
            'pendidikan' => 'S1 / S2 Pendidikan Vokasi Terakreditasi',
            'keahlian' => 'Guru Bahasa Indonesia & Digital Learning',
            'email' => 'rina-marlina@smktelkom-sda.sch.id',
            'deskripsi' => 'Guru pengajar profesional yang berdedikasi membimbing dan mengasah kompetensi siswa SMK Telkom Sidoarjo di bidang Guru Bahasa Indonesia.',
        ],
        [
            'nama' => 'Eko Prasetyo, S.Kom',
            'slug' => 'eko-prasetyo-skom',
            'foto' => 'images/profileguru/adi.webp',
            'mapel' => 'Guru Produktif SIJA',
            'jabatan' => 'Guru Produktif SIJA',
            'pendidikan' => 'S1 / S2 Pendidikan Vokasi Terakreditasi',
            'keahlian' => 'Guru Produktif SIJA & Digital Learning',
            'email' => 'eko-prasetyo@smktelkom-sda.sch.id',
            'deskripsi' => 'Guru pengajar profesional yang berdedikasi membimbing dan mengasah kompetensi siswa SMK Telkom Sidoarjo di bidang Guru Produktif SIJA.',
        ],
        [
            'nama' => 'Tri Wahyuni, S.Pd',
            'slug' => 'tri-wahyuni-spd',
            'foto' => 'images/profileguru/ike.webp',
            'mapel' => 'Guru Pendidikan Agama',
            'jabatan' => 'Guru Pendidikan Agama',
            'pendidikan' => 'S1 / S2 Pendidikan Vokasi Terakreditasi',
            'keahlian' => 'Guru Pendidikan Agama & Digital Learning',
            'email' => 'tri-wahyuni@smktelkom-sda.sch.id',
            'deskripsi' => 'Guru pengajar profesional yang berdedikasi membimbing dan mengasah kompetensi siswa SMK Telkom Sidoarjo di bidang Guru Pendidikan Agama.',
        ],
        [
            'nama' => 'Aris Munandar, S.T',
            'slug' => 'aris-munandar-st',
            'foto' => 'images/profileguru/adi.webp',
            'mapel' => 'Guru Produktif TJAT',
            'jabatan' => 'Guru Produktif TJAT',
            'pendidikan' => 'S1 / S2 Pendidikan Vokasi Terakreditasi',
            'keahlian' => 'Guru Produktif TJAT & Digital Learning',
            'email' => 'aris-munandar@smktelkom-sda.sch.id',
            'deskripsi' => 'Guru pengajar profesional yang berdedikasi membimbing dan mengasah kompetensi siswa SMK Telkom Sidoarjo di bidang Guru Produktif TJAT.',
        ],
        [
            'nama' => 'Fitri Handayani, S.Kom',
            'slug' => 'fitri-handayani-skom',
            'foto' => 'images/profileguru/pabror.webp',
            'mapel' => 'Guru Produktif SIJA',
            'jabatan' => 'Guru Produktif SIJA',
            'pendidikan' => 'S1 / S2 Pendidikan Vokasi Terakreditasi',
            'keahlian' => 'Guru Produktif SIJA & Digital Learning',
            'email' => 'fitri-handayani@smktelkom-sda.sch.id',
            'deskripsi' => 'Guru pengajar profesional yang berdedikasi membimbing dan mengasah kompetensi siswa SMK Telkom Sidoarjo di bidang Guru Produktif SIJA.',
        ],
        [
            'nama' => 'Hadi Pranoto, S.Pd',
            'slug' => 'hadi-pranoto-spd',
            'foto' => 'images/profileguru/ike.webp',
            'mapel' => 'Guru Pendidikan Jasmani & Olahraga',
            'jabatan' => 'Guru Pendidikan Jasmani & Olahraga',
            'pendidikan' => 'S1 / S2 Pendidikan Vokasi Terakreditasi',
            'keahlian' => 'Guru Pendidikan Jasmani & Olahraga & Digital Learning',
            'email' => 'hadi-pranoto@smktelkom-sda.sch.id',
            'deskripsi' => 'Guru pengajar profesional yang berdedikasi membimbing dan mengasah kompetensi siswa SMK Telkom Sidoarjo di bidang Guru Pendidikan Jasmani & Olahraga.',
        ],
        [
            'nama' => 'Lestari Indah, S.Pd',
            'slug' => 'lestari-indah-spd',
            'foto' => 'images/profileguru/pabror.webp',
            'mapel' => 'Guru Sejarah Indonesia',
            'jabatan' => 'Guru Sejarah Indonesia',
            'pendidikan' => 'S1 / S2 Pendidikan Vokasi Terakreditasi',
            'keahlian' => 'Guru Sejarah Indonesia & Digital Learning',
            'email' => 'lestari-indah@smktelkom-sda.sch.id',
            'deskripsi' => 'Guru pengajar profesional yang berdedikasi membimbing dan mengasah kompetensi siswa SMK Telkom Sidoarjo di bidang Guru Sejarah Indonesia.',
        ],
        [
            'nama' => 'Gunawan Wibisono, S.Kom',
            'slug' => 'gunawan-wibisono-skom',
            'foto' => 'images/profileguru/adi.webp',
            'mapel' => 'Guru Produktif SIJA',
            'jabatan' => 'Guru Produktif SIJA',
            'pendidikan' => 'S1 / S2 Pendidikan Vokasi Terakreditasi',
            'keahlian' => 'Guru Produktif SIJA & Digital Learning',
            'email' => 'gunawan-wibisono@smktelkom-sda.sch.id',
            'deskripsi' => 'Guru pengajar profesional yang berdedikasi membimbing dan mengasah kompetensi siswa SMK Telkom Sidoarjo di bidang Guru Produktif SIJA.',
        ],
        [
            'nama' => 'Yulia Safitri, S.Pd',
            'slug' => 'yulia-safitri-spd',
            'foto' => 'images/profileguru/ike.webp',
            'mapel' => 'Guru Bimbingan Konseling',
            'jabatan' => 'Guru Bimbingan Konseling',
            'pendidikan' => 'S1 / S2 Pendidikan Vokasi Terakreditasi',
            'keahlian' => 'Guru Bimbingan Konseling & Digital Learning',
            'email' => 'yulia-safitri@smktelkom-sda.sch.id',
            'deskripsi' => 'Guru pengajar profesional yang berdedikasi membimbing dan mengasah kompetensi siswa SMK Telkom Sidoarjo di bidang Guru Bimbingan Konseling.',
        ],
        [
            'nama' => 'Andik Irawan, S.T',
            'slug' => 'andik-irawan-st',
            'foto' => 'images/profileguru/adi.webp',
            'mapel' => 'Guru Produktif TJAT',
            'jabatan' => 'Guru Produktif TJAT',
            'pendidikan' => 'S1 / S2 Pendidikan Vokasi Terakreditasi',
            'keahlian' => 'Guru Produktif TJAT & Digital Learning',
            'email' => 'andik-irawan@smktelkom-sda.sch.id',
            'deskripsi' => 'Guru pengajar profesional yang berdedikasi membimbing dan mengasah kompetensi siswa SMK Telkom Sidoarjo di bidang Guru Produktif TJAT.',
        ],
        [
            'nama' => 'Nita Anggraeni, S.Kom',
            'slug' => 'nita-anggraeni-skom',
            'foto' => 'images/profileguru/pabror.webp',
            'mapel' => 'Guru Produktif SIJA',
            'jabatan' => 'Guru Produktif SIJA',
            'pendidikan' => 'S1 / S2 Pendidikan Vokasi Terakreditasi',
            'keahlian' => 'Guru Produktif SIJA & Digital Learning',
            'email' => 'nita-anggraeni@smktelkom-sda.sch.id',
            'deskripsi' => 'Guru pengajar profesional yang berdedikasi membimbing dan mengasah kompetensi siswa SMK Telkom Sidoarjo di bidang Guru Produktif SIJA.',
        ],
        [
            'nama' => 'Rudi Hartono, S.Pd',
            'slug' => 'rudi-hartono-spd',
            'foto' => 'images/profileguru/ike.webp',
            'mapel' => 'Guru Seni Budaya',
            'jabatan' => 'Guru Seni Budaya',
            'pendidikan' => 'S1 / S2 Pendidikan Vokasi Terakreditasi',
            'keahlian' => 'Guru Seni Budaya & Digital Learning',
            'email' => 'rudi-hartono@smktelkom-sda.sch.id',
            'deskripsi' => 'Guru pengajar profesional yang berdedikasi membimbing dan mengasah kompetensi siswa SMK Telkom Sidoarjo di bidang Guru Seni Budaya.',
        ],
        [
            'nama' => 'Megawati, S.Pd',
            'slug' => 'megawati-spd',
            'foto' => 'images/profileguru/pabror.webp',
            'mapel' => 'Guru PPKn',
            'jabatan' => 'Guru PPKn',
            'pendidikan' => 'S1 / S2 Pendidikan Vokasi Terakreditasi',
            'keahlian' => 'Guru PPKn & Digital Learning',
            'email' => 'megawati@smktelkom-sda.sch.id',
            'deskripsi' => 'Guru pengajar profesional yang berdedikasi membimbing dan mengasah kompetensi siswa SMK Telkom Sidoarjo di bidang Guru PPKn.',
        ],
        [
            'nama' => 'Dani Kurniawan, S.Kom',
            'slug' => 'dani-kurniawan-skom',
            'foto' => 'images/profileguru/adi.webp',
            'mapel' => 'Guru Produktif SIJA',
            'jabatan' => 'Guru Produktif SIJA',
            'pendidikan' => 'S1 / S2 Pendidikan Vokasi Terakreditasi',
            'keahlian' => 'Guru Produktif SIJA & Digital Learning',
            'email' => 'dani-kurniawan@smktelkom-sda.sch.id',
            'deskripsi' => 'Guru pengajar profesional yang berdedikasi membimbing dan mengasah kompetensi siswa SMK Telkom Sidoarjo di bidang Guru Produktif SIJA.',
        ],
        [
            'nama' => 'Suryanto, S.T',
            'slug' => 'suryanto-st',
            'foto' => 'images/profileguru/ike.webp',
            'mapel' => 'Guru Produktif TJAT',
            'jabatan' => 'Guru Produktif TJAT',
            'pendidikan' => 'S1 / S2 Pendidikan Vokasi Terakreditasi',
            'keahlian' => 'Guru Produktif TJAT & Digital Learning',
            'email' => 'suryanto@smktelkom-sda.sch.id',
            'deskripsi' => 'Guru pengajar profesional yang berdedikasi membimbing dan mengasah kompetensi siswa SMK Telkom Sidoarjo di bidang Guru Produktif TJAT.',
        ],
        [
            'nama' => 'Ratna Sari, S.Pd',
            'slug' => 'ratna-sari-spd',
            'foto' => 'images/profileguru/adi.webp',
            'mapel' => 'Guru Kimia Terapan',
            'jabatan' => 'Guru Kimia Terapan',
            'pendidikan' => 'S1 / S2 Pendidikan Vokasi Terakreditasi',
            'keahlian' => 'Guru Kimia Terapan & Digital Learning',
            'email' => 'ratna-sari@smktelkom-sda.sch.id',
            'deskripsi' => 'Guru pengajar profesional yang berdedikasi membimbing dan mengasah kompetensi siswa SMK Telkom Sidoarjo di bidang Guru Kimia Terapan.',
        ],
        [
            'nama' => 'Indra Kusuma, S.Kom',
            'slug' => 'indra-kusuma-skom',
            'foto' => 'images/profileguru/pabror.webp',
            'mapel' => 'Guru Produktif SIJA',
            'jabatan' => 'Guru Produktif SIJA',
            'pendidikan' => 'S1 / S2 Pendidikan Vokasi Terakreditasi',
            'keahlian' => 'Guru Produktif SIJA & Digital Learning',
            'email' => 'indra-kusuma@smktelkom-sda.sch.id',
            'deskripsi' => 'Guru pengajar profesional yang berdedikasi membimbing dan mengasah kompetensi siswa SMK Telkom Sidoarjo di bidang Guru Produktif SIJA.',
        ],
        [
            'nama' => 'Dina Mariana, S.Pd',
            'slug' => 'dina-mariana-spd',
            'foto' => 'images/profileguru/ike.webp',
            'mapel' => 'Guru Fisika Terapan',
            'jabatan' => 'Guru Fisika Terapan',
            'pendidikan' => 'S1 / S2 Pendidikan Vokasi Terakreditasi',
            'keahlian' => 'Guru Fisika Terapan & Digital Learning',
            'email' => 'dina-mariana@smktelkom-sda.sch.id',
            'deskripsi' => 'Guru pengajar profesional yang berdedikasi membimbing dan mengasah kompetensi siswa SMK Telkom Sidoarjo di bidang Guru Fisika Terapan.',
        ],
        [
            'nama' => 'Agung Wicaksono, S.T',
            'slug' => 'agung-wicaksono-st',
            'foto' => 'images/profileguru/pabror.webp',
            'mapel' => 'Guru Produktif TJAT',
            'jabatan' => 'Guru Produktif TJAT',
            'pendidikan' => 'S1 / S2 Pendidikan Vokasi Terakreditasi',
            'keahlian' => 'Guru Produktif TJAT & Digital Learning',
            'email' => 'agung-wicaksono@smktelkom-sda.sch.id',
            'deskripsi' => 'Guru pengajar profesional yang berdedikasi membimbing dan mengasah kompetensi siswa SMK Telkom Sidoarjo di bidang Guru Produktif TJAT.',
        ],
        [
            'nama' => 'Lina Rosita, S.Kom',
            'slug' => 'lina-rosita-skom',
            'foto' => 'images/profileguru/adi.webp',
            'mapel' => 'Guru Produktif SIJA',
            'jabatan' => 'Guru Produktif SIJA',
            'pendidikan' => 'S1 / S2 Pendidikan Vokasi Terakreditasi',
            'keahlian' => 'Guru Produktif SIJA & Digital Learning',
            'email' => 'lina-rosita@smktelkom-sda.sch.id',
            'deskripsi' => 'Guru pengajar profesional yang berdedikasi membimbing dan mengasah kompetensi siswa SMK Telkom Sidoarjo di bidang Guru Produktif SIJA.',
        ],
        [
            'nama' => 'Bayu Pamungkas, S.Pd',
            'slug' => 'bayu-pamungkas-spd',
            'foto' => 'images/profileguru/ike.webp',
            'mapel' => 'Guru Muatan Lokal & Bahasa Jawa',
            'jabatan' => 'Guru Muatan Lokal & Bahasa Jawa',
            'pendidikan' => 'S1 / S2 Pendidikan Vokasi Terakreditasi',
            'keahlian' => 'Guru Muatan Lokal & Bahasa Jawa & Digital Learning',
            'email' => 'bayu-pamungkas@smktelkom-sda.sch.id',
            'deskripsi' => 'Guru pengajar profesional yang berdedikasi membimbing dan mengasah kompetensi siswa SMK Telkom Sidoarjo di bidang Guru Muatan Lokal & Bahasa Jawa.',
        ],
        [
            'nama' => 'Kartika Candra, S.Kom',
            'slug' => 'kartika-candra-skom',
            'foto' => 'images/profileguru/adi.webp',
            'mapel' => 'Guru Produktif SIJA',
            'jabatan' => 'Guru Produktif SIJA',
            'pendidikan' => 'S1 / S2 Pendidikan Vokasi Terakreditasi',
            'keahlian' => 'Guru Produktif SIJA & Digital Learning',
            'email' => 'kartika-candra@smktelkom-sda.sch.id',
            'deskripsi' => 'Guru pengajar profesional yang berdedikasi membimbing dan mengasah kompetensi siswa SMK Telkom Sidoarjo di bidang Guru Produktif SIJA.',
        ],
        [
            'nama' => 'Wawan Sulistyo, S.T',
            'slug' => 'wawan-sulistyo-st',
            'foto' => 'images/profileguru/pabror.webp',
            'mapel' => 'Guru Produktif TJAT',
            'jabatan' => 'Guru Produktif TJAT',
            'pendidikan' => 'S1 / S2 Pendidikan Vokasi Terakreditasi',
            'keahlian' => 'Guru Produktif TJAT & Digital Learning',
            'email' => 'wawan-sulistyo@smktelkom-sda.sch.id',
            'deskripsi' => 'Guru pengajar profesional yang berdedikasi membimbing dan mengasah kompetensi siswa SMK Telkom Sidoarjo di bidang Guru Produktif TJAT.',
        ],
    ],
    'staff_karyawan' => [
        [
            'nama' => 'Nurul Hidayati, S.E',
            'slug' => 'nurul-hidayati',
            'foto' => 'images/profileguru/rachel.webp',
            'jabatan' => 'Kepala Urusan Keuangan',
            'pendidikan' => 'S1 Akuntansi Keuangan',
            'keahlian' => 'Administrasi & Billing',
            'email' => 'keuangan@smktelkom-sda.sch.id',
            'deskripsi' => 'Mengelola sistem administrasi keuangan dan pembayaran pendidikan siswa secara akuntabel dan transparan.',
        ],
        [
            'nama' => 'Budi Prasetyo, A.Md',
            'slug' => 'budi-prasetyo',
            'foto' => 'images/profileguru/adi.webp',
            'jabatan' => 'Kepala Tata Usaha',
            'pendidikan' => 'D3 Manajemen Informatika',
            'keahlian' => 'Administrasi & Kearsipan',
            'email' => 'tatausaha@smktelkom-sda.sch.id',
            'deskripsi' => 'Mengkoordinasikan pelayanan administrasi persuratan, data pokok pendidikan (Dapodik), dan layanan kesiswaan.',
        ],
        [
            'nama' => 'Rian Hidayat, S.Kom',
            'slug' => 'rian-hidayat',
            'foto' => 'images/profileguru/pabror.webp',
            'jabatan' => 'Laboran & IT Support',
            'pendidikan' => 'S1 Teknik Informatika',
            'keahlian' => 'Hardware & Server Maintenance',
            'email' => 'itsupport@smktelkom-sda.sch.id',
            'deskripsi' => 'Memastikan seluruh perangkat komputer laboratorium, server e-learning, dan jaringan WiFi sekolah berjalan prima.',
        ],
        [
            'nama' => 'Dewi Anggraini, S.Hum',
            'slug' => 'dewi-anggraini',
            'foto' => 'images/profileguru/ike.webp',
            'jabatan' => 'Pustakawan Digital',
            'pendidikan' => 'S1 Ilmu Perpustakaan',
            'keahlian' => 'Literasi Digital & E-Library',
            'email' => 'perpustakaan@smktelkom-sda.sch.id',
            'deskripsi' => 'Mengelola koleksi buku fisik, e-book, jurnal sains, serta fasilitas ruang baca digital SMK Telkom Sidoarjo.',
        ],
        [
            'nama' => 'Slamet Riyadi, S.AP',
            'slug' => 'slamet-riyadi',
            'foto' => 'images/profileguru/adi.webp',
            'jabatan' => 'Staf Administrasi Kepegawaian',
            'pendidikan' => 'S1 Administrasi Publik',
            'keahlian' => 'Kepegawaian & SDM Sekolah',
            'email' => 'sdm@smktelkom-sda.sch.id',
            'deskripsi' => 'Menangani administrasi tenaga pendidik dan kependidikan, rekrutmen internal, serta pembinaan kompetensi berkala.',
        ],
        [
            'nama' => 'Citra Maharani, S.I.Kom',
            'slug' => 'citra-maharani',
            'foto' => 'images/profileguru/rachel.webp',
            'jabatan' => 'Staf Hubungan Masyarakat (Humas)',
            'pendidikan' => 'S1 Ilmu Komunikasi',
            'keahlian' => 'Public Relations & Branding',
            'email' => 'humas@smktelkom-sda.sch.id',
            'deskripsi' => 'Mengelola publikasi resmi sekolah, media sosial, kemitraan media massa, serta komunikasi dengan orang tua murid.',
        ],
    ],
];
